sudo: false
language: node_js
node_js:
- 'stable'
- '10'
- '8'
- '6'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
stages:
  - lint
  - test
  - coveralls
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: coveralls
      script: yarn coveralls
env:
  global:
    # COVERALLS_REPO_TOKEN=
      secure: "I8mDH0n2DQHAPvUFEV/ZNmrMNYTJxgywg8+P3yuCAWwQkZeXQi0DWG+6VUpOylaRhL/4kCdZK9gnJD2MfrqvNqVLDUqBK3tTmZVoyqqJEdE0UdEHcPncAPmxWrG98sDjqFN9r4nWeizHvyA1fNRQHRN56Zy+DcQWjgEhHJaYeNA="
